# Miraibot config file
# Either leave entry blank or remove completly to use the defaults..

# General config
ConfigName: Mirai-testing
ConfigAuthor: Ashley Towns <ashleyis@me.com>
BotNick: mirai
BotUser: ikerawks
BotFullname: I eat cheese
PreferredTrigger: \!

# Plugin setup
Plugins:
  - Plugin: test-plugin  # 'core' plugins are stored in mirai/plugins/
    Update: core
    Restrict: ashleyis!oohbouncy@*
  - Plugin: regex-plugin
    Update: core
  - Plugin: ey-plugin 
    Update: core
    Settings:
      WebappName: oompfserver
      WebappRoot: /data/..
  # - Plugin: pivotal-plugin
  #   Update: core
  #   Settings:
  #     Token: 
  #     DefaultProject: 77418
  # - Plugin: zero-plugin
  #   Update: core
  # - Plugin: twitterinfo-plugin
  #   Update: core
  # - Plugin: test-http # a plugin can auto update from a website..
  #   Update: http
  #   URL: http://www.google.com
  #   Frequency: 1d
  # - Plugin: test-git # or you can have plugins auto update from a git repo..
  #   Update: git
  #   URL: git://github.com/aktowns/mirai-gitplugin.git
  #   Frequency: 1d

# Mirai contains a built-in thin server for plugins to integrate with
# for things like web callbacks
WebServer:
  Address: 0.0.0.0
  Port: 3000
  Enabled: true

# Server setup
# alot of settings can be left blank for defaults.
Servers:
  - Server: avoidinspace
    Hosts:
      - irc.avoidinspace.com:6667 # <server>:[+ ssl]<port>
      - kirby.avoidinspace.com
      - peach.avoidinspace.com
    Chans: [main, bots, 0]
    ServerPassword:
    ServerReconnect: true
    DisabledPlugins: [eval]
    # override the defaults.
    BotNick:
    BotUser:
    BotFullname:


